export const templates = [
    'Diapers',
    'Diaper wetting',
    'Diaper messing',
    'Pants wetting',
    'Pants messing',
    'Force me into diapers',
    'Diaper check (front)',
    'Diaper check (back)',
    'Diaper check (legband)',
    'Change my diaper',
    'Change my clothes',
    'Force regress me',
    'Spank me',
    'Take my picture (with face)',
    'Take my picture (no face)',
    'Buttpats',
    'Bathroom off limits',
    'Take me to the potty',
    'Cuddle me',
    'Kiss my forehead',
    'Kiss my lips',
    'Lewd me in diapers',
    'Lewd me without diapers',
    'Lewd others',
    'Pick me up',
    'Play hypnosis',
    'Tease me playfully',
    'Embarrass me',
    'Bully me',
    'Play with other Littles',
    'Lewd with other Littles',
    'Locking clothes',
    'Bondage',
    'Bratting',
    'Care for multiple Littles',
    'Lewd with multiple Littles',
    'Nursing (breasts)',
    'Feed me food',
    'Feed me a bottle',
];