export const templates = [
    'Diapers',
    'Wetting',
    'Messing',
    'Accidents without diapers',
    'Regression',
    'Diaper checks',
    'Diaper changes',
    'Feeding',
    'Teasing',
    'Bratting',
    'Forced/CNC',
    'Bondage',
    'Spanking',
    'Cuddles',
    'Doting kisses',
    'Kissing',
    'Sexual acts',
    'Pictures'
];